login
WebAhead12/clinic-client pull request #8
Opened 2022-01-02 13:55 UTC by halakhamis07

2022-01-03 08:37 UTC, Zahimues commented
you forgot to fetch by email when the log is false
if u can do it tell me if u dont want i will

2022-01-03 12:46 UTC, Karyum commented
> you forgot to fetch by email when the log is false if u can do it tell me if u dont want i will

@Zahimues that should be a different pull request, we will do it later

2022-01-03 12:49 UTC, Karyum requested changes

2022-01-03 12:49 UTC, Karyum commented on src/pages/Login/index.jsx
> +import { useState, useRef } from 'react'
useRef is no being used

2022-01-03 12:49 UTC, Karyum commented on src/pages/Login/index.jsx
> +    gov_id: '',
change `gov_id` to `govId`

I know it's annoying but there are other changes on this pull request so I said why not

2022-01-03 12:49 UTC, Karyum commented on src/pages/Login/index.jsx
> +        setError('error with fetch')
`Please try again, or login by phone/email`

2022-01-03 12:49 UTC, Karyum commented on src/pages/Login/index.jsx
> +        window.localStorage.setItem('access_token', res.data.access_token)
use `react-router-dom` to move the user to the homepage once the request is done

2022-01-04 10:36 UTC, Karyum approved these changes

2022-01-04 10:36 UTC, merged